version: "2.1"
services:
  smokeping:
          image: casperklein/smokeping:latest
    #hostname: 
    container_name: smokeping
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config:/etc/smokeping
      - ./data:/var/lib/smokeping
    ports:
      - 80:80
    restart: always
    stop_grace_period: 1m
