services:
  smokeping:
    image: casperklein/smokeping:latest
    container_name: smokeping
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config:/config
      - ./data:/data
    ports:
      - "80:80"
    restart: always
    stop_grace_period: 1m
